version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: SM-Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SM
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq :
    image: rabbitmq:3-management
    container_name: SM-RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq



volumes:
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local
